export interface Book {
  name: string
  author: string
  thoughts?: string
  isRecommended?: boolean
  isRecommendedComments?: string
  willReRead?: boolean
  willReReadComments?: string
  status: "reading" | "completed"
  completedYear?: number
  notionLink?: string
  tags?: string[]
}

export const books: Book[] = [
  {
    name: "Thinking Fast and Slow",
    author: "Daniel Kahneman",
    status: "reading",
    tags: ["Psychology"],
  },
  {
    name: "The Recursive Book on Recursion",
    author: "Al Sweigart",
    status: "reading",
    tags: ["Tech"],
  },
  {
    name: "Investing 101",
    author: "Michele Cagan",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Finance"],
  },
  {
    name: "The Compound Effect",
    author: "Darren Hardy",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Self-help"],
  },
  // {
  //   name: "Why Bharat Matters",
  //   author: "S Jaishankar",
  //   status: "reading",
  // },
  {
    name: "Shiva Trilogy: Part 1 - The Immortals of Meluha",
    author: "Amish",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Mythological Fiction"],
  },
  {
    name: "Shiva Trilogy: Part 2 - The Secret of the Nagas",
    author: "Amish",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Mythological Fiction"],
  },
  {
    name: "Shiva Trilogy: Part 3 - The Oath of the Vayuputras",
    author: "Amish",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Mythological Fiction"],
  },
  {
    name: "21 career hacks for developers: A career guide for Software Engineers",
    author: "Pradeep Sharma",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Tech"],
  },
  {
    name: "Merlin's Tour of The Universe",
    author: "Neil deGrasse Tyson",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Astronomy", "Science"],
  },
  {
    name: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    status: "completed",
    completedYear: 2025,
    willReRead: false,
    isRecommended: true,
    tags: ["Business"],
  },
  {
    name: "Never Split the Difference",
    author: "Chris Voss",
    status: "completed",
    completedYear: 2025,
    isRecommended: true,
    willReRead: true,
    tags: ["Psychology"],
  },
  {
    name: "The Art of Thinking Clearly",
    author: "Rolf Dobelli",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    tags: ["Self-help", "Psychology"],
  },
  {
    name: "Proof: The uncertain science of certainity",
    status: "completed",
    author: "Adam Kucharski",
    isRecommended: false,
    isRecommendedComments:
      "Skim read the last few chapters, worth if you're curious about maths origins, and probability.",
    willReRead: false,
    completedYear: 2025,
    tags: ["Science"],
  },
  {
    name: "Don't believe everything you think",
    author: "Joseph Nguyen",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Don-t-believe-everything-you-think-1a35e52c1e1980678745d20f7dfbe991",
    tags: ["Self-help"],
  },
  {
    name: "Rich Dad Poor Dad",
    author: "Robert Kiyosaki",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2023,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Rich-Dad-Poor-Dad-21a5e52c1e1980a889e8e77c8e246fb8",
    tags: ["Finance"],
  },
  {
    name: "Attitude is Everything",
    author: "Jeff Keller",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Attitude-is-Everything-21a5e52c1e1980eea754cdd32f05cba4",
    tags: ["Self-help"],
  },
  {
    name: "Drive",
    author: "Daniel H. Pink",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2024,
    thoughts: "Available on Notion",
    notionLink: "https://www.notion.so/Drive-21a5e52c1e1980418328df1a89134d1a",
    tags: ["Self-help"],
  },
  {
    name: "Transform your Self Talk",
    author: "Nikk Trenton",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Transform-your-Self-Talk-21a5e52c1e198012b09bf9a77f3aa614",
    tags: ["Self-help"],
  },
  {
    name: "Rework",
    author: "Jason Fried, David Heinemeier Hansson",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink: "https://www.notion.so/Rework-21a5e52c1e1980bb92a2e2c89ce4028a",
    tags: ["Self-help", "Business"],
  },
  {
    name: "The Art of Laziness",
    author: "Library Mindset",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2025,
    tags: ["Self-help"],
  },
  {
    name: "Eat that Frog",
    author: "Brian Tracy",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2024,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Eat-that-Frog-21a5e52c1e198080a866da32fe7305ed",
    tags: ["Self-help", "Productivity"],
  },
  {
    name: "Daiva",
    author: "K. Hari Kumar",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Indian History"],
  },
  {
    name: "The Almanack of Naval Ravikant",
    author: "Eric Jorgenson",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2024,
    tags: ["Self-help"],
  },
  {
    name: "Flirting with Stocks",
    author: "Anil Lamba",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Finance"],
  },
  {
    name: "Focus on What Matters",
    author: "Darius Foroux",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2024,
    tags: ["Self-help"],
  },
  {
    name: "Do Epic Shit",
    author: "Ankur Warikoo",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2023,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Do-Epic-Shit-21a5e52c1e198088885dcdcb1086f802",
    tags: ["Self-help"],
  },
  {
    name: "Ikigai",
    author: "Francesc Miralles and Hector Garcia",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2024,
    thoughts: "Available on Notion",
    notionLink: "https://www.notion.so/Ikigai-21a5e52c1e19807791c9cdf3d04978c4",
    tags: ["Self-help"],
  },
  {
    name: "Mahagatha",
    author: "Satyarth Nayak",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Indian History"],
  },
  {
    name: "The Power of Your Subconscious Mind",
    author: "Joseph Murphy",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/The-Power-of-Your-Subconscious-Mind-21a5e52c1e198014b887ea60a667b15f",
    tags: ["Self-help"],
  },
  {
    name: "The Psychology of Money",
    author: "Morgan Housel",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2024,
    tags: ["Finance"],
  },
  {
    name: "Steve Jobs",
    author: "Walter Isaacson",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2024,
    tags: ["Biography"],
  },
  {
    name: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    tags: ["Self-help"],
  },
  {
    name: "Atomic Habits",
    author: "James Clear",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2023,
    tags: ["Self-help"],
  },
  {
    name: "Deep Work",
    author: "Cal Newport",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Productivity"],
  },
  {
    name: "Who Moved My Cheese",
    author: "Spencer Johnson",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Who-Moved-My-Cheese-21a5e52c1e1980c59de9f115f31f0f18",
    tags: ["Self-help"],
  },
  {
    name: "Start with Why",
    author: "Simon Sinek",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    thoughts: "Available on Notion",
    notionLink:
      "https://www.notion.so/Start-with-Why-21a5e52c1e1980c9a1c1e0f5469e1f3c",
    tags: ["Self-help", "Business"],
  },
  {
    name: "Zero to One",
    author: "Peter Thiel",
    status: "completed",
    isRecommended: true,
    willReRead: true,
    completedYear: 2025,
    tags: ["Business"],
  },
  {
    name: "Remote",
    author: "Jason Fried, David Heinemeier Hansson",
    status: "completed",
    isRecommended: false,
    willReRead: false,
    completedYear: 2025,
    tags: ["Business"],
  },
  {
    name: "Principles",
    author: "Ray Dalio",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Self-help"],
  },
  {
    name: "Advanced React: Deep dives, Investigations, Performance Patterns and Techniques",
    author: "Nadia Makarevich",
    status: "completed",
    isRecommended: true,
    willReRead: false,
    completedYear: 2025,
    tags: ["Tech"],
  },
]
