import { v4 as uuid } from "uuid";
export const projects = [
  {
    id: uuid(),
    name: "Subreddit Finder",
    description: "Always find the best subreddit for your query",
    image: "/projects/subreddit-finder.png",
    labels: ["Next.js", "TypeScript", "TailwindCSS", "Gemini 2.0 Flash"],
    date: "March 2025",
    sourceCode: "https://github.com/dev-shetty/subreddit-finder",
    liveUrl: "https://subreddit-finder.shetty.me/",
  },
  {
    id: uuid(),
    name: "Tatva - Know your Geography",
    description:
      "Explore countries interactively with real-time search and rich visuals. Built this for levels.fyi",
    image: "/projects/tatva.png",
    labels: ["Next.js", "TypeScript", "TailwindCSS"],
    date: "August 2024",
    sourceCode: "https://github.com/dev-shetty/tatva",
    liveUrl: "https://tatva-country.vercel.app/",
  },
  {
    id: uuid(),
    name: "Sankalp",
    description:
      "Event registration portal and dashboard, for all the events conducted by SOSC.",
    image: "/projects/sankalp.png",
    labels: ["Next.js", "TypeScript", "TailwindCSS", "MERN"],
    date: "October 2023",
    sourceCode: "https://github.com/so-sc/Sankalp",
    liveUrl: "https://sankalp.sosc.org.in/",
  },
  {
    id: uuid(),
    name: "Finvest",
    description:
      "Web application for providing financial education, and mutual savings using Pots",
    image: "/projects/finvest.png",
    labels: ["Next.js", "TypeScript", "TailwindCSS"],
    date: "February 2024",
    sourceCode: "https://github.com/dev-shetty/rudra-parsec",
    liveUrl: null,
  },
  {
    id: uuid(),
    name: "ORIME - Bus Tracking",
    description:
      "Built a real-time bus tracking system for school children using React Native and Nestjs as College Project",
    image: "/projects/orime.png",
    labels: ["Nestjs", "React Native", "TypeScript", "PostgreSQL"],
    date: "December 2024",
    sourceCode: "https://github.com/dev-shetty/bus-tracking-system",
  },
  {
    id: uuid(),
    name: "Tiles",
    description:
      "A real-time collaboration platform that enables users to collaboratively place and interact with tiles on a shared canvas.",
    image: "/projects/tiles.jpg",
    labels: ["Typescript", "Next.js", "Express.js", "MongoDB", "Sockets"],
    date: "September 2023",
    sourceCode: "https://github.com/dev-shetty/tiles",
    liveUrl: "https://placetile.vercel.app/",
  },
  {
    id: uuid(),
    name: "Rudraksh",
    description:
      "A web-based platform enabling farmers to identify plant diseases through image uploads, enhancing crop health management.",
    image: "/projects/rudraksh.jpg",
    labels: ["Next.js", "TypeScript", "TailwindCSS", "API"],
    date: "August 2023",
    sourceCode: "https://github.com/dev-shetty/Rudraksh",
    liveUrl: "https://rudraksh.vercel.app/",
  },
  {
    id: uuid(),
    name: "Chromatico",
    description:
      "A color generator website that will help you find a good color combination for your upcoming projects or designs.",
    image: "/projects/chromatico.png",
    labels: ["React.js", "TypeScript", "TailwindCSS"],
    date: "March 2023",
    sourceCode: "https://github.com/dev-shetty/Chromatico",
    liveUrl: "https://chromatico.vercel.app/",
  },
  {
    id: uuid(),
    name: "Razer Website Clone",
    description:
      "Cloned the Landing page of Razer website using modern web technologies.",
    image: "/projects/razer-clone.png",
    labels: ["Typescript", "React.js", "TailwindCSS"],
    date: "February 2023",
    sourceCode: "https://github.com/dev-shetty/Razer-Clone",
    liveUrl: "https://razer-clone-iota.vercel.app",
  },
  {
    id: uuid(),
    name: "Rolex Website Clone",
    description: "A clone of Rolex website Landing Page.",
    image: "/projects/rolex-clone.png",
    labels: ["Typescript", "React.js", "TailwindCSS"],
    date: "February 2023",
    sourceCode: "https://github.com/dev-shetty/Rolex-Clone",
    liveUrl: "https://rolex-clone.vercel.app/",
  },
  {
    id: uuid(),
    name: "Expense Tracker",
    description:
      "A comprehensive utility application for expense and stock tracking with a clean and minimalist user interface.",
    image: "/projects/expense-tracker.jpeg",
    labels: ["Javascript", "React.js", "TailwindCSS", "Express.js", "MongoDB"],
    date: "December 2022",
    sourceCode: "https://github.com/dev-shetty/Expense-Tracker",
    liveUrl: null,
  },
  {
    id: uuid(),
    name: "Clouds",
    description:
      "A user-friendly website for the CS Department's Clouds Organization platform for department events and office bearer details.",
    image: "/projects/clouds.png",
    labels: ["Javascript", "React.js", "CSS"],
    date: "December 2022",
    sourceCode: "https://github.com/dev-shetty/Clouds",
    liveUrl: "https://cs-clouds.netlify.app",
  },
  {
    id: uuid(),
    name: "API Forever",
    description:
      "My first ever react project, it is a simple website that uses public APIs like Jokes, Quotes, etc.",
    image: "/projects/api-forever.png",
    labels: ["Javascript", "React.js", "CSS", "API"],
    date: "August 2022",
    sourceCode: "https://github.com/dev-shetty/API-Forever",
    liveUrl: "https://api-forever.netlify.app",
  },
];
